### ISSUE TITLE
Support for older GCC versions (-std=c++0x)

### ISSUE THREAD

**Issue by Code-ReaQtor** [Tessil/hopscotch-map#12]
Hi,

It seems compiling this library using old GCC version with incomplete C++11 support (-std=c++0x) is not currently possible. Are there any plans to support this?

Cheers!

**Comment by Tessil** [comment]
Hi,

No plan, but I may look into it depending on how much changes there is to do. Which version of GCC do you use?

**Comment by Code-ReaQtor** [comment]
@Tessil

I am using GCC 4.4.7 which is default in CentOS 6.5.

Thanks.

**Comment by Tessil** [comment]
Sorry that would be too old. 

I added some support for GCC 4.8(.4, couldn't test with an older revision), but older would require too much changes.
