### ISSUE TITLE
Containers are not copyable anymore

### ISSUE THREAD

**Issue by jcelerier** [Tessil/hopscotch-map#17]
The following code fails to compile for me with current git master : 

    #include <hopscotch_map.h>
    void t()
    {
      tsl::hopscotch_map<int, int> m;
      auto m2 = m;
    }

with the following error : 

    In file included from /usr/include/c++/6.3.1/bits/stl_tempbuf.h:60:0,
                     from /usr/include/c++/6.3.1/bits/stl_algo.h:62,
                     from /usr/include/c++/6.3.1/algorithm:62,
                     from /home/jcelerier/travail/i-score/API/3rdparty/hopscotch-map/src/hopscotch_map.h:28,
                     from /home/jcelerier/travail/i-score/API/OSSIA/ossia/ossia.cpp:1:
    /usr/include/c++/6.3.1/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>; _Args = {const tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>&}]’:
    /usr/include/c++/6.3.1/bits/stl_uninitialized.h:75:18:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>*, std::vector<tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>, std::allocator<tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false> > > >; _ForwardIterator = tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>*; bool _TrivialValueTypes = false]’
    /usr/include/c++/6.3.1/bits/stl_uninitialized.h:126:15:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>*, std::vector<tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>, std::allocator<tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false> > > >; _ForwardIterator = tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>*]’
    /usr/include/c++/6.3.1/bits/stl_uninitialized.h:281:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>*, std::vector<tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>, std::allocator<tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false> > > >; _ForwardIterator = tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>*; _Tp = tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>]’
    /usr/include/c++/6.3.1/bits/stl_vector.h:324:31:   required from ‘std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false>; _Alloc = std::allocator<tsl::detail_hopscotch_hash::hopscotch_bucket<std::pair<int, int>, 62u, false> >]’
    /home/jcelerier/travail/i-score/API/3rdparty/hopscotch-map/src/hopscotch_hash.h:568:5:   required from here
    /usr/include/c++/6.3.1/bits/stl_construct.h:75:7: error: use of deleted function ‘tsl::detail_hopscotch_hash::hopscotch_bucket<ValueType, NeighborhoodSize, StoreHash>::hopscotch_bucket(const tsl::detail_hopscotch_hash::hopscotch_bucket<ValueType, NeighborhoodSize, StoreHash>&) [with ValueType = std::pair<int, int>; unsigned int NeighborhoodSize = 62u; bool StoreHash = false]’
         { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /home/jcelerier/travail/i-score/API/3rdparty/hopscotch-map/src/hopscotch_map.h:36:0,
                     from /home/jcelerier/travail/i-score/API/OSSIA/ossia/ossia.cpp:1:
    /home/jcelerier/travail/i-score/API/3rdparty/hopscotch-map/src/hopscotch_hash.h:217:5: note: declared here
         hopscotch_bucket(const hopscotch_bucket& bucket) = delete;
         ^~~~~~~~~~~~~~~~
    ninja: build stopped: subcommand failed.

**Comment by Tessil** [comment]
Thanks, made the correction. I removed a copy constructor by mistake.

**Comment by jcelerier** [comment]
yep, it works ! thanks for the reactivity.
