### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by mpusz** [Tessil/hopscotch-map#18]
On last 2 releases (1.2, 1.2.1) I have compilation/linker issues with hopscotch_map:
1. gcc 5.3.0 debug
hopscotch_hash.h:130: undefined reference to `tsl::mod_growth_policy<std::ratio<3l, 1l> >::MIN_BUCKETS_SIZE
2. VS 2015
hopscotch_hash.h(1557): warning C4100: 'hash': unreferenced formal parameter (compiling source file C:\chprojects\ets_falcon\source\matchserver-cpp\src\common\CentralLimitOrderBook.cpp)
I admit that the last one is probably a compiler bug but anyway it might be good to investigate what is going on. It helps adding (void)hash; in line 1565

Are you aware of those?

**Comment by Tessil** [comment]
Thank you for the report.

For the first point, it seems some versions of clang and gcc couldn't take the private `static const std::size_t MIN_BUCKETS_SIZE` into `std::max` directly. By using an intermediate local variable, it seems to work (still have to understand why).

For the second point, it's not a compiler bug. The variable is never used (and optimized away) when StoreHash is false. VS 2015 detects it while clang and gcc never warned me. I have added the `(void) hash` to the code.

**Comment by mpusz** [comment]
Adding:
`template<class GrowthFactor>
const std::size_t mod_growth_policy<GrowthFactor>::MIN_BUCKETS_SIZE = 2;`
below the class definition solved the compilation issue for me.
