### ISSUE TITLE
Searching by key and hash

### ISSUE THREAD

**Issue by mpusz** [Tessil/hopscotch-map#21]
Hi,

I would like to know your opinion on the possibility to provide additionally a precomputed hash value to find() member function. I would love such a feature as I am often looking for the same key value in many different hash containers and each of them recalculates the hash value for that value all over again. If find function had signature like:
```
iterator find(const Key& key, Hash* hash = nullptr);
<or>
iterator find(const Key& key, Hash hash = m_hash(key));
```
I would save a lot of time on calculating the same hash value all over again.

Best

Mat

**Comment by Tessil** [comment]
Hi,

It would be possible. I quickly created a branch with the feature. It contains extra find methods which take the hash in parameter:

`iterator find(const Key& key, std::size_t hash)`

```c++
tsl::hopscotch_map<std::string, int> map = {{"one", 1}, {"two", 2}};
map.find("one", map.hash_function()("one"));
```

I have to think a bit to see if there is a better way to do and then extends it to the other lookup methods before merging it to the master.

**Comment by mpusz** [comment]
Nice :+1:

**Comment by Tessil** [comment]
I added the parameter to the others lookups methods for consistency and merged the changes to the master.
