### ISSUE TITLE
operator= is broken

### ISSUE THREAD

**Issue by jcelerier** [Tessil/hopscotch-map#22]
The following won't build on current git head: 

```
tsl::hopscotch_map<std::string, std::string> s;
tsl::hopscotch_map<std::string, std::string> s2 = s; // initialization is ok
s2 = s; // operator= fails
```

It worked by f5b7e62900503d387cdc126cbf45bdb27ace0a19 .

A quick bisect told me that fd765fb6bd3349604975408953bac5fd1c7d7709 is the commit that introduced breakage; 838413d works.

**Comment by Tessil** [comment]
Thank you for the report. 

Made the correction, I removed the copy/move constructor/operator of hopscotch_bucket too quickly. Same problem as before (#17).

**Comment by jcelerier** [comment]
thanks!
