### ISSUE TITLE
difference_type/unsigned int conversion warning

### ISSUE THREAD

**Issue by Reputeless** [Tessil/hopscotch-map#25]
`difference_type`/`unsigned int` conversion warning is generated for 64-bit build in the following line:
https://github.com/Tessil/hopscotch-map/blob/fc9994548df8bd462fe19564229fb9aeb353258b/src/hopscotch_hash.h#L191
```cpp
m_iprime = std::distance(tsl::detail_hopscotch_hash::PRIMES.begin(), it_prime);
```

**Comment by Tessil** [comment]
Made the correction, than you!
