### ISSUE TITLE
count() does not work for hopscotch_set

### ISSUE THREAD

**Issue by mpusz** [Tessil/hopscotch-map#26]
It seems that there is an issue with `count()` for tsl::hopscotch_set. In the simple following example:
```cpp
tsl::hopscotch_set<std::string> s;
s.find(std::string{"abc"});
s.count(std::string{"abc"});
```
I get "no matching overloaded function found" in [hopscotch_hash.h:1124](https://github.com/Tessil/hopscotch-map/blob/v1.3.1/src/hopscotch_hash.h#L1124) on Visual Studio 2015 for `count()` however `find()` works OK.

Note that such code is also OK:
```cpp
tsl::hopscotch_map<std::string, int> s;
s.find(std::string{"abc"});
s.count(std::string{"abc"});
```

**Comment by Tessil** [comment]
Thank you for the report. The bug should be fixed.
