### ISSUE TITLE
bug on building a simple map

### ISSUE THREAD

**Issue by yecol** [Tessil/hopscotch-map#27]
Dear Tessil, 
I spent nearly one day on a bug and finally find it may come out from the hopscotch-map.
Here is a test file extracted from our log and a simple test program to help you to reproduce it.
The key file contains 187414 unique values, and expected the map should have the same number of size. However, the size of built map is 187353. 
https://www.dropbox.com/s/hf35bq88t7ixve0/keys.dat?dl=0
https://www.dropbox.com/s/a62cdfq3kr3nuao/maptest.cpp?dl=0

could you help to debug it? Many thanks!

**Comment by Tessil** [comment]
Hi,

Thank you very much for your report. It's quite an awful bug.

The problem arises from a corner case where the neighbourhood of a bucket get over-flooded after a rehash. I wrongly assumed it should not happen as when the bucket array gets bigger the elements should be more separated. In your case, a cluster of values congregated close to a bucket after the rehash process making the swapping impossible for some new values. They ended-up in the overflow list which was not handled well
