### ISSUE TITLE
Thread-safety ?

### ISSUE THREAD

**Issue by jcelerier** [Tessil/hopscotch-map#3]
Which guarantees does the data structures offer ? Are they at least at strong (so not very strong) than equivalent std:: containers ? (i.e. multiple threads doing only lookups in the map at the same time should be safe).

Thanks !

**Comment by Tessil** [comment]
The guarantees are the same as the std. If you only do lookups from multiple threads there will be no problem.

Just don't call the value() method of the returned iterator to modify the value and don't share the iterators between threads if you plan to modify them.

**Comment by jcelerier** [comment]
> Just don't call the value() method of the returned iterator to modify the value 

Even if my value is an std::atomic ?

**Comment by Tessil** [comment]
Concurrent modifications should be fine then.

**Comment by jcelerier** [comment]
cool, thanks !
