### ISSUE TITLE
Precalculated hashes

### ISSUE THREAD

**Issue by Bouncner** [Tessil/hopscotch-map#38]
Hi tessil,

we are working on a research database which uses radix clustering. Here, we first hash a value, determine a partition accordingly, and then create a hash table for each partition.

Since we already calculated a hash for the partitioning, I was wondering why there is no insert method that supports precalculated hashes.
Am I overseeing something or has there just not been a reason to implement yet?

Besides that, I really dig your work here on GitHub. Keep it up!

**Comment by Tessil** [comment]
Hello,

The main reason is mainly, as you said, that there was no reason to implement it. I didn't have the need for it in my projects and nobody asked for it.

The second reason is that when I added the precalculated hash for lookup functions, I didn't add it to the insert functions because it's a bit more dangerous. If the user provides a wrong hash for the value, the map may end up in an undefined state, a value may end up in a bucket where it doesn't belong.

Though I will see if I can add it and leave the responsibility to the user to provide the correct hash.

I'm currently in holiday for the next few weeks so I'll not be able to check the issue more deeply and do the implementation before my return.

**Comment by mpusz** [comment]
Hi,

First of all thank you very much for your project and excellent support.

It was me that requested precalculated hash support for lookup some time
ago. I am happy to inform that we had excellent experience with that
feature and that is why I submitted P0920 proposal for the next ISO C++
Committee meeting (http://wg21.link/p0920 - the link should become active
in a few days fron now).

Also just FYI, based on your excellent work I submitted a
http://wg21.link/P0919 that was already accepted for C++20.

Thank you very much for your continous support for the C++ Community!

Best

Mat

niedz., 16 wrz 2018, 13:20 użytkownik Thibaut <notifications@github.com>
napisał:

**Comment by Tessil** [comment]
Hello,

Thank you very much for your kind words and for the work done for these proposals.

Note that if P0919 is implemented you could do better than the alternative mentioned in section 4 of P0920. The following code could work even in a multi-threaded context without any branching:
```c++
template<typename T>
class hash_cache {
public:
    hash_cache(const T& value, std::size_t hash): m_value(value), m_hash(hash) {
    }

    std::size_t hash() const {
        return m_hash;
    }
    
    friend bool operator==(const T& lhs, const hash_cache& rhs) {
        return lhs == rhs.m_value;
    }
    
    friend bool operator==(const hash_cache& lhs, const T& rhs) {
        return lhs.m_value == rhs;
    }
    
private:    
    const T& m_value;
    std::size_t m_hash;
};

template<typename T>
class hash {
public:
    using transparent_key_equal = std::equal_to<>;
    
    std::size_t operator()(const hash_cache<T>& v) const {
        return v.hash();
    }
    
    // For insertions or normal lookups
    std::size_t operator()(const T& v) const {
        return std::hash<T>()(v);
    }
};

int main() {
    const std::string str = "Potential long string.";
    const std::size_t hash_value = std::hash<std::string>()(str);
    
    std::unordered_map<std::string, int, hash<std::string>> map;
    map.find(hash_cache<std::string>(str, hash_value));
}
```

It's not as clean and easy as having the extra `hash` parameter, but it can be an interesting option if the proposal doesn't go through.

**Comment by mpusz** [comment]
Hi,

Even though I think it is an abuse of transparent lookup, it is so
interesting and out-of-the-box that I like it ;-)

Thanks!

Mat

wt., 9 paź 2018 o 21:11 użytkownik Thibaut <notifications@github.com>
napisał:

**Comment by Tessil** [comment]
I'll close the issue for now but if someone really need to possibility to use precalculated hashes for insertion, feel free to comment, I may reconsider the possibility to add it in the master branch.
