### ISSUE TITLE
Compile error on latest commit

### ISSUE THREAD

**Issue by jcelerier** [Tessil/hopscotch-map#41]
I have to change hopscotch_hash.h:375 into `if constexpr(StoreHash) {`, else I get the following error: 

    tsl/hopscotch_hash.h:376: error : no type named 'hash_type' in 'tsl::detail_hopscotch_hash::hopscotch_bucket_hash<false>'
                return std::numeric_limits<typename bucket_hash::hash_type>::max();
                                           ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~

(and indeed, a ctrl-f of hash_type does not yield anything). 
I don't set the StoreHash parameter to true anywhere in my code but it seems that my compiler (gcc-8.2) still checks the validity of the branch.

**Comment by Tessil** [comment]
Hi,

Effectively, the variable was moved during a refactoring and I completely forgot about `hopscotch_bucket::max_size()`. It's in fact not necessary as using `StoreHash` doesn't limit the size of the hash map anymore.

Though do you call `hopsctoch_map/set::max_size()` in your code somewhere? Or was the error generated even without that (which shouldn't be as a non-called method of a templated class [should not be instantiated](https://stackoverflow.com/questions/183108/is-object-code-generated-for-unused-template-class-methods))?

Anyway, I added a test that calls `hopsctoch_map/set::max_size()` explicitly to avoid the problem in the future. Sorry for the inconvenience.

Thank you for the report.
