### ISSUE TITLE
Repeated use of operator[] coredumps in one particular case

### ISSUE THREAD

**Issue by maxkiva** [Tessil/hopscotch-map#42]
Hi
This simple use case coredumps with corrupt heap

class Foo 
{
    public:
        Foo() : foo_(nullptr) { } 
        ~Foo()
        {
            delete[] foo_;
            foo_ = nullptr;
        }

        void fromString( const std::string& s ) 
        {
            delete foo_;
            foo_ = new char[ s.size() + 1  ];  
            std::strcpy( foo_, s.c_str() );
        }
        const char* foo() const { return foo_; }
    private:
        char* foo_;
};

#ifdef USE_STD_UOM
typedef std::unordered_map<std::string,Foo> test_map;
#else
typedef tsl::hopscotch_map<std::string,Foo> test_map;
#endif

int main()
{
    test_map m;
    for( int i = 0; i < 100; ++i )
    {   
        // build key
        std::string key = "key_";
        key += std::to_string(i);
        // build value;
        std::string value = "value_";
        value += std::to_string(i);
        // insert key and get ref to inserted value
        Foo& foo = m[key];
        // populate value
        foo.fromString( value );
        std::cout << key << ":" << foo.foo() << '\n';
    }   
}

Works fine with std::unordered_map or google dense map

**Comment by Tessil** [comment]
Hi,

Your class `Foo` doesn't respect the [rule of five](https://en.cppreference.com/w/cpp/language/rule_of_three#Rule_of_five). Moving or copying a `Foo` will end-up in a double free and potential read after free. 

The reason that it works with `std::unordered_map` is that it uses nodes, it thus never calls the move/copy constructor of `Foo` and only copy pointers to `Foo`.

Both `google::dense_hash_map` (which, as tested, also results in an error with your code when there is a rehash) and `tsl::hopscotch_map` use open-addressing and have to copy/move `Foo` objects around, but the copy/move constructor of `Foo` results in undefined behavior.

Make sure to respect the rule of five if you manage resources manually in your class.
