### ISSUE TITLE
contains()

### ISSUE THREAD

**Issue by Reputeless** [Tessil/hopscotch-map#47]
Member functions `contains(const Key&)` and `contains(const Key&, size_t hash)` were added to standard associative containers in C++20.

- https://wg21.link/p0458r2
- https://wg21.link/p0920r2
- https://en.cppreference.com/w/cpp/container/unordered_map/contains

Adding these functions will improve compatibility with the latest standard features.

**Comment by Tessil** [comment]
Hi,

Yes, it's effectively a good idea to add them. I made the changes.
