### ISSUE TITLE
MS VS 2017 compiler error

### ISSUE THREAD

**Issue by hordi** [Tessil/hopscotch-map#50]
Simplest code produces compilation error (MS VS 2017 Version 15.9.17).

    tsl::bhopscotch_map<uint64_t, uint64_t> m3;

    m3[10] = 100;

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'return': cannot convert from 'const unsigned __int64' to 'unsigned __int64 &'	fastest_hash	c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\hopscotch_hash.h	538	
Error	C2440	'return': cannot convert from 'const unsigned __int64' to 'unsigned __int64 &'	fastest_hash	c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\hopscotch_hash.h	541	

Full output log:
1>------ Build started: Project: fastest_hash, Configuration: Release x64 ------
1>main.cpp
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\hopscotch_hash.h(538): error C2440: 'return': cannot convert from 'const unsigned __int64' to 'unsigned __int64 &'
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\hopscotch_hash.h(538): note: Conversion loses qualifiers
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\hopscotch_hash.h(1073): note: see reference to function template instantiation 'unsigned __int64 &tsl::detail_hopscotch_hash::hopscotch_hash<std::pair<const _Kty,_Ty>,tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<_Kty>,std::equal_to<_Ty>,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::KeySelect,tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<_Kty>,std::equal_to<_Ty>,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::ValueSelect,Hash,KeyEqual,Allocator,62,false,GrowthPolicy,std::map<_Kty,_Ty,Compare,Allocator>>::hopscotch_iterator<false>::value<ValueSelect,0x0>(void) const' being compiled
1>        with
1>        [
1>            _Kty=uint64_t,
1>            _Ty=uint64_t,
1>            Hash=std::hash<uint64_t>,
1>            KeyEqual=std::equal_to<uint64_t>,
1>            Allocator=std::allocator<std::pair<const uint64_t,uint64_t>>,
1>            GrowthPolicy=tsl::hh::power_of_two_growth_policy<2>,
1>            Compare=std::less<uint64_t>,
1>            ValueSelect=tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<uint64_t>,std::equal_to<uint64_t>,std::less<uint64_t>,std::allocator<std::pair<const uint64_t,uint64_t>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::ValueSelect
1>        ]
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\hopscotch_hash.h(1071): note: see reference to function template instantiation 'unsigned __int64 &tsl::detail_hopscotch_hash::hopscotch_hash<std::pair<const _Kty,_Ty>,tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<_Kty>,std::equal_to<_Ty>,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::KeySelect,tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<_Kty>,std::equal_to<_Ty>,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::ValueSelect,Hash,KeyEqual,Allocator,62,false,GrowthPolicy,std::map<_Kty,_Ty,Compare,Allocator>>::hopscotch_iterator<false>::value<ValueSelect,0x0>(void) const' being compiled
1>        with
1>        [
1>            _Kty=uint64_t,
1>            _Ty=uint64_t,
1>            Hash=std::hash<uint64_t>,
1>            KeyEqual=std::equal_to<uint64_t>,
1>            Allocator=std::allocator<std::pair<const uint64_t,uint64_t>>,
1>            GrowthPolicy=tsl::hh::power_of_two_growth_policy<2>,
1>            Compare=std::less<uint64_t>,
1>            ValueSelect=tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<uint64_t>,std::equal_to<uint64_t>,std::less<uint64_t>,std::allocator<std::pair<const uint64_t,uint64_t>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::ValueSelect
1>        ]
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\bhopscotch_map.h(447): note: see reference to function template instantiation 'unsigned __int64 &tsl::detail_hopscotch_hash::hopscotch_hash<std::pair<const _Kty,_Ty>,tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<_Kty>,std::equal_to<_Ty>,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::KeySelect,tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<_Kty>,std::equal_to<_Ty>,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::ValueSelect,Hash,KeyEqual,Allocator,62,false,GrowthPolicy,std::map<_Kty,_Ty,Compare,Allocator>>::operator []<unsigned __int64,ValueSelect,0x0>(K &&)' being compiled
1>        with
1>        [
1>            _Kty=uint64_t,
1>            _Ty=uint64_t,
1>            Hash=std::hash<uint64_t>,
1>            KeyEqual=std::equal_to<uint64_t>,
1>            Allocator=std::allocator<std::pair<const uint64_t,uint64_t>>,
1>            GrowthPolicy=tsl::hh::power_of_two_growth_policy<2>,
1>            Compare=std::less<uint64_t>,
1>            ValueSelect=tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<uint64_t>,std::equal_to<uint64_t>,std::less<uint64_t>,std::allocator<std::pair<const uint64_t,uint64_t>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::ValueSelect,
1>            K=unsigned __int64
1>        ]
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\bhopscotch_map.h(447): note: see reference to function template instantiation 'unsigned __int64 &tsl::detail_hopscotch_hash::hopscotch_hash<std::pair<const _Kty,_Ty>,tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<_Kty>,std::equal_to<_Ty>,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::KeySelect,tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<_Kty>,std::equal_to<_Ty>,std::less<_Ty>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::ValueSelect,Hash,KeyEqual,Allocator,62,false,GrowthPolicy,std::map<_Kty,_Ty,Compare,Allocator>>::operator []<unsigned __int64,ValueSelect,0x0>(K &&)' being compiled
1>        with
1>        [
1>            _Kty=uint64_t,
1>            _Ty=uint64_t,
1>            Hash=std::hash<uint64_t>,
1>            KeyEqual=std::equal_to<uint64_t>,
1>            Allocator=std::allocator<std::pair<const uint64_t,uint64_t>>,
1>            GrowthPolicy=tsl::hh::power_of_two_growth_policy<2>,
1>            Compare=std::less<uint64_t>,
1>            ValueSelect=tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<uint64_t>,std::equal_to<uint64_t>,std::less<uint64_t>,std::allocator<std::pair<const uint64_t,uint64_t>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::ValueSelect,
1>            K=unsigned __int64
1>        ]
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\bhopscotch_map.h(447): note: while compiling class template member function 'T &tsl::bhopscotch_map<uint64_t,T,std::hash<_Kty>,std::equal_to<_Kty>,std::less<Key>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::operator [](Key &&)'
1>        with
1>        [
1>            T=uint64_t,
1>            _Kty=uint64_t,
1>            Key=uint64_t,
1>            _Ty=uint64_t
1>        ]
1>c:\dev\projects\fastest_hash\src\main.cpp(121): note: see reference to function template instantiation 'T &tsl::bhopscotch_map<uint64_t,T,std::hash<_Kty>,std::equal_to<_Kty>,std::less<Key>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>::operator [](Key &&)' being compiled
1>        with
1>        [
1>            T=uint64_t,
1>            _Kty=uint64_t,
1>            Key=uint64_t,
1>            _Ty=uint64_t
1>        ]
1>c:\dev\projects\fastest_hash\src\main.cpp(119): note: see reference to class template instantiation 'tsl::bhopscotch_map<uint64_t,uint64_t,std::hash<_Kty>,std::equal_to<_Kty>,std::less<Key>,std::allocator<std::pair<const _Kty,_Ty>>,62,false,tsl::hh::power_of_two_growth_policy<2>>' being compiled
1>        with
1>        [
1>            _Kty=uint64_t,
1>            Key=uint64_t,
1>            _Ty=uint64_t
1>        ]
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\hopscotch_growth_policy.h(202): note: see reference to class template instantiation 'std::array<size_t,40>' being compiled
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\hopscotch_hash.h(541): error C2440: 'return': cannot convert from 'const unsigned __int64' to 'unsigned __int64 &'
1>c:\dev\projects\fastest_hash\src\hopscotch-map-master\include\tsl\hopscotch_hash.h(541): note: Conversion loses qualifiers
1>Done building project "fastest_hash.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Tessil** [comment]
Hi,

Thank you very much for the report. the last commit should fix the issue.

Thibaut
