### ISSUE TITLE
Building with -fno-exceptions

### ISSUE THREAD

**Issue by geniiii** [Tessil/hopscotch-map#51]
Using this library is currently impossible when building with the `-fno-exceptions` flag. Is it possible for exceptions to be replaced with `abort()` when using said flag?

**Comment by Tessil** [comment]
Hi,

I will see to add support for `-fno-exceptions` when I have a bit of time. The [Tessil/robin-map](https://github.com/Tessil/robin-map) project supports this if needed in the meantime.

**Comment by Tessil** [comment]
Done, please let me know if there is any problem.
