### ISSUE TITLE
Recommended means to update key?

### ISSUE THREAD

**Issue by tashrifsanil** [Tessil/hopscotch-map#54]
Hi! Is there any recommended/built in way to update the key of the hashmap ? Without touching the library the only thing I can think of is erasing a key value pair, and adding it back with the updated key but that's an expensive operation. I'd appreciate any help I can get, and I'm loving the library so far!

**Comment by Tessil** [comment]
Hello,

There isn't really any better way currently than erasing the key and reinserting it after modification. As the hash of the modified key can be completely different of the original one, I don't see much possibilities to optimize the operation.

`std::unordered_map` has an `extract` method to extract a node that can then be reinserted. It's useful to avoid a node allocation on insertion but it isn't necessary for open-addressing hash maps like hopscotch-map as they don't need to allocate memory on insertion (outside of a potential rehash).

**Comment by tashrifsanil** [comment]
Thanks for getting back to me! I did not know that it doesn't allocate memory on insertion, that was pretty insightful and interesting!! Thanks again!!
