### ISSUE TITLE
Move-Only, Non-Default-Constructible Types not supported as values

### ISSUE THREAD

**Issue by elemakil** [Tessil/hopscotch-map#8]
The documentation states that there's _"Support for move-only and non-default constructible key/value"_, however, unless I'm mistaken in what is meant with that, I don't think that is true or needs further clarification.

**Edit:** I did some more digging and I'm going with _"needs further clarification"_. The issue is that the move / copy constructor has to be defined `noexcept` in order to be used by the `hopscotch_map`. This is not API compatible with `std::unordered_{map,set}` and should be noted as such.

----

I've cooked up a small example (see below) which does not compile with error

````
[...] error: call to implicitly-deleted copy constructor of 'value_type' [...]
````

I'm on Mac OSX 10.11.6 with the system compiler; `clang++ --version` reports

````
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
````

I'm attempting to compile the example with

````
clang++ -W -Wall -Wextra -std=c++11 -I hopscotch-map -o test test.cpp
````

I have uploaded the full error log [here](http://pastebin.com/EjUwsGA4).

----

````c++
#include <memory>

struct MoveOnly {
    explicit MoveOnly(int i)
        : m_data(i){}
    MoveOnly(MoveOnly && other)
        : m_data(std::move(other.m_data)){}
    MoveOnly(const MoveOnly &) = delete;
    MoveOnly & operator=(const MoveOnly &) = delete;
    MoveOnly & operator=(MoveOnly &&) = delete;
private:
    int m_data;
};

#include "hopscotch_map.h"

#include <string>

class Foo {
public:
    tsl::hopscotch_map<std::string, MoveOnly> m_db;
    Foo()
        : m_db(){}
};

int main(){
    Foo f;
}
````

**Comment by Tessil** [comment]
Thank you for the report.

If you change:

```c++
MoveOnly(MoveOnly && other)
        : m_data(std::move(other.m_data)){}
```

to

```c++
MoveOnly(MoveOnly && other) noexcept
        : m_data(std::move(other.m_data)){}
```

it should work.

The main problem comes from the rehash function that needs either a copy constructible element or a no throw move constructible element.

I will see if I can change to make it works even with a move constructor that may throw (as it seems to work with `std::unordered_map`).

**Comment by Tessil** [comment]
Yes I think I will need to change the documentation. It doesn't seem possible to use objects with a throwable move-constructor only in a safe way.

The problem occurs during rehash which need to have some exception guarantees. 

Here is how I proceed now:
- If the key-value is nothrow movable, I create a larger bucket array and if everything goes well I can safely move each key-value. The only exception that may occur is when I create the larger bucket array, but at this point I didn't modify the original map, we're safe.
- Else, I create a larger bucket array and copy each element to this new array. At the end I swap (noexcept) the two bucket arrays. If something goes wrong, the original is intact.

Now what do I do if I have a throwable move-constructor? I can't keep the exception guarantee, if a move fails I don't have any backup of the moved value to restore the situation.

I could add a note like the 'push_back' of std::vector which waive the guarantee in this case:

> In overload (1), if T's move constructor is not noexcept and T is not CopyInsertable into *this, vector will use the throwing move constructor. If it throws, the guarantee is waived and the effects are unspecified.

```c++
struct move_only {
    explicit move_only(int i) : m_data(i) {
    }
    
    move_only(move_only&& other): m_data(std::move(other.m_data)) {
        // Intentionally mess-up with the data
        other.m_data = -1;
        m_data = -1;
        
        throw std::runtime_error("Exception in move.");
    }
    
    move_only(const move_only&) = delete;
    move_only& operator=(const move_only&) = delete;
    move_only& operator=(move_only&&) = delete;

    int m_data;
};

int main() {
    std::vector<move_only> vect;
    vect.reserve(5);
    
    for(std::size_t i = 0; i < 5; i++) {
        vect.emplace_back(i);
    }
    
    assert(vect.capacity() == vect.size());
    
    
    try {
        vect.emplace_back(0);
    }
    catch(...) {
        std::cout << "exception" << std::endl;
    }
    
    // [-1, 1, 2, 3, 4] instead of [0, 1, 2, 3, 4]
    for(std::size_t i = 0; i < vect.size(); i++) {
        std::cout << vect[i].m_data << std::endl;
    }
}
```

The `std::unordered_map` doesn't have this problem as it uses chaining. On rehash it can just move some pointers of the linked list, it doesn't need to call the move constructor of the key-values. In open-addressing, it is not possible.

So two solutions: either waive the exception guarantee on this condition like `std::vector` or forbid throwable move-constructible only object.

**Comment by Tessil** [comment]
Kept the second solution in the end. I added some checks to get a more readable compile error and updated the documentation.
