### ISSUE TITLE
VS C4503 warning

### ISSUE THREAD

**Issue by mpusz** [Tessil/hopscotch-map#9]
When I try to use tsl::hopscotch_map instead of std::unordered_map I often end up with VS C4503 warning. Do you have any good BKMs on how to handle such issues?

**Comment by mpusz** [comment]
BTW, I do not have any complicated structure of containers in containers. I observe that for simple/flat one hopscotch_map<in_place_string<CharT, MaxSize, Traits>, ptr_type> for at least operator[]() and erase(Key) operations. For in_place_string definition look here: https://github.com/mpusz/in_place_string.

**Comment by Tessil** [comment]
Could you try [this branch](https://github.com/Tessil/hopscotch-map/tree/vs_decorated_name_length_warning).

I'm able to instantiate things like 
`tsl::hopscotch_map<int, tsl::hopscotch_map<int, std::vector<std::pair<int, std::map<int, int>>>>> inner_map;` without any warning.

**Comment by mpusz** [comment]
I confirm that branch compiles fine for my case. Are there any side effects of that code (e.g. lower performance)?

**Comment by Tessil** [comment]
The performances should be exactly the same. I just moved some inner-classes into the detail namespace reducing the length of the identifiers.
